OSOYOO_IR.onPressEvent(RemoteButton.num5, function () {
    basic.showNumber(5)
    basic.showIcon(IconNames.Heart)
    basic.pause(1000)
    basic.showNumber(5)
})
OSOYOO_IR.onPressEvent(RemoteButton.num4, function () {
    basic.showNumber(4)
    basic.showIcon(IconNames.Heart)
    basic.pause(1000)
    basic.showNumber(4)
})
OSOYOO_IR.onPressEvent(RemoteButton.num6, function () {
    basic.showNumber(6)
    basic.showIcon(IconNames.Heart)
    basic.pause(1000)
    basic.showNumber(6)
})
OSOYOO_IR.onPressEvent(RemoteButton.num8, function () {
    basic.showNumber(8)
    basic.showIcon(IconNames.Heart)
    basic.pause(1000)
    basic.showNumber(8)
})
OSOYOO_IR.onPressEvent(RemoteButton.num7, function () {
    basic.showNumber(7)
    basic.showIcon(IconNames.Heart)
    basic.pause(1000)
    basic.showNumber(7)
})
OSOYOO_IR.onPressEvent(RemoteButton.num0, function () {
    basic.showNumber(0)
    basic.showIcon(IconNames.Heart)
    basic.pause(1000)
    basic.showNumber(0)
})
OSOYOO_IR.onPressEvent(RemoteButton.num1, function () {
    basic.showNumber(1)
    basic.showIcon(IconNames.Heart)
    basic.pause(1000)
    basic.showNumber(1)
})
OSOYOO_IR.onPressEvent(RemoteButton.num2, function () {
    basic.showNumber(2)
    basic.showIcon(IconNames.Heart)
    basic.pause(1000)
    basic.showNumber(2)
})
OSOYOO_IR.onPressEvent(RemoteButton.num9, function () {
    basic.showNumber(9)
    basic.showIcon(IconNames.Heart)
    basic.pause(1000)
    basic.showNumber(9)
})
OSOYOO_IR.onPressEvent(RemoteButton.num3, function () {
    basic.showNumber(3)
    basic.showIcon(IconNames.Heart)
    basic.pause(1000)
    basic.showNumber(3)
})
OSOYOO_IR.init(Pins.P3)
basic.pause(1000)
basic.showIcon(IconNames.Heart)
